/*
 * Copyright 2019 The JimDB Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dspb/function.proto

package io.jimdb.pb;

public final class Function {
  private Function() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code dspb.FunctionID}
   */
  public enum FunctionID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>kFuncHeartbeat = 0;</code>
     */
    kFuncHeartbeat(0),
    /**
     * <code>kFuncRangeRequest = 1;</code>
     */
    kFuncRangeRequest(1),
    /**
     * <code>kFuncSchedule = 2;</code>
     */
    kFuncSchedule(2),
    /**
     * <code>kFuncAdmin = 3;</code>
     */
    kFuncAdmin(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>kFuncHeartbeat = 0;</code>
     */
    public static final int kFuncHeartbeat_VALUE = 0;
    /**
     * <code>kFuncRangeRequest = 1;</code>
     */
    public static final int kFuncRangeRequest_VALUE = 1;
    /**
     * <code>kFuncSchedule = 2;</code>
     */
    public static final int kFuncSchedule_VALUE = 2;
    /**
     * <code>kFuncAdmin = 3;</code>
     */
    public static final int kFuncAdmin_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FunctionID valueOf(int value) {
      return forNumber(value);
    }

    public static FunctionID forNumber(int value) {
      switch (value) {
        case 0: return kFuncHeartbeat;
        case 1: return kFuncRangeRequest;
        case 2: return kFuncSchedule;
        case 3: return kFuncAdmin;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FunctionID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FunctionID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FunctionID>() {
            public FunctionID findValueByNumber(int number) {
              return FunctionID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.jimdb.pb.Function.getDescriptor().getEnumTypes().get(0);
    }

    private static final FunctionID[] VALUES = values();

    public static FunctionID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FunctionID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dspb.FunctionID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023dspb/function.proto\022\004dspb*Z\n\nFunctionI" +
      "D\022\022\n\016kFuncHeartbeat\020\000\022\025\n\021kFuncRangeReque" +
      "st\020\001\022\021\n\rkFuncSchedule\020\002\022\016\n\nkFuncAdmin\020\003B" +
      "\022\n\020io.jimdb.pbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
